//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuePAT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITE> CITE { get; set; }
        public virtual DbSet<CLASSIFICATION> CLASSIFICATION { get; set; }
        public virtual DbSet<CMNT> CMNT { get; set; }
        public virtual DbSet<COMPANY> COMPANY { get; set; }
        public virtual DbSet<DISCUSSION> DISCUSSION { get; set; }
        public virtual DbSet<FAMILY> FAMILY { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACK { get; set; }
        public virtual DbSet<HELP> HELP { get; set; }
        public virtual DbSet<LAW_STATUS> LAW_STATUS { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<PATENT> PATENT { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PROVINCE> PROVINCE { get; set; }
        public virtual DbSet<PROXY> PROXY { get; set; }
        public virtual DbSet<USR> USR { get; set; }
    }
}
