//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuePAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROXY
    {
        public string APP_NUM { get; set; }
        public string AGENT_ID { get; set; }
        public string AGENCY { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual PATENT PATENT { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
