//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Module_of_QuePAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCUSSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISCUSSION()
        {
            this.CMNT = new HashSet<CMNT>();
            this.RELATED_FILED = new HashSet<RELATED_FILED>();
        }
    
        public decimal DISC_ID { get; set; }
        public decimal PUT_UP_USR_ID { get; set; }
        public string TOPIC { get; set; }
        public string CONTENT { get; set; }
        public System.DateTime INIT_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMNT> CMNT { get; set; }
        public virtual USR USR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELATED_FILED> RELATED_FILED { get; set; }
    }
}
