//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Module_of_QuePAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USR()
        {
            this.CMNT = new HashSet<CMNT>();
            this.DISCUSSION = new HashSet<DISCUSSION>();
        }
    
        public decimal USR_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime REG_TIME { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string COMPANY { get; set; }
        public string ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMNT> CMNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCUSSION> DISCUSSION { get; set; }
    }
}
